services:
  medusa:
    build: .
    container_name: medusa
    environment:
      - JWT_SECRET=key
      - COOKIE_SECRET=key
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://postgres:9745775893@postgres:9745775893/postgres
    ports:
      - "9000:9000"
      - "7001:7001"
    depends_on:
      - postgres
    networks:
      - medusa-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9745775893
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - medusa-network

networks:
  medusa-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local